### PR TITLE
Async support for other operations

### PR DESCRIPTION
**Pull request by benmccallum**
Adds on to work in issue https://github.com/landmarkhw/Dapper.GraphQL/issues/1 and previous PR https://github.com/landmarkhw/Dapper.GraphQL/pull/5.

### CODE REVIEW

**Comment by benmccallum** [comment]
Having an exception in the Insert person async and Update person async tests I created. Stack trace below. Not exactly sure what would be causing a "System.InvalidCastException : Unable to cast object of type 'Dapper.GraphQL.Test.DbConnectionWrapper' to type 'System.Data.Common.DbConnection'.". I mean that would make sense since DbConnectionWrapper is only implementing IDbConnection and isn't a DbConnection per se. Is that Dapper accepting the interface in method sigs but casting to the concrete implementation incorrectly?

=====
Test Name:	INSERT person asynchronously succeeds
Test FullName:	Dapper.GraphQL.Test.InsertTests.InsertPersonAsync
Test Source:	C:\src\Dapper.GraphQL\Dapper.GraphQL.Test\InsertTests.cs : line 108
Test Outcome:	Failed
Test Duration:	0:00:05.465

Result StackTrace:	
at Dapper.SqlMapper.<QueryAsync>d__31`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Dapper.GraphQL.SqlInsertContextExtensions.<ExecuteWithSqlIdentityAsync>d__1`1.MoveNext() in C:\src\Dapper.GraphQL\Dapper.GraphQL\Extensions\SqlInsertContextExtensions.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Dapper.GraphQL.Test.InsertTests.<InsertPersonAsync>d__3.MoveNext() in C:\src\Dapper.GraphQL\Dapper.GraphQL.Test\InsertTests.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Result Message:	System.InvalidCastException : Unable to cast object of type 'Dapper.GraphQL.Test.DbConnectionWrapper' to type 'System.Data.Common.DbConnection'.

**Comment by dougrday** [comment]
Try calling `connection.Open();` before doing Async operations.  Looking at the Dapper docs, they do that there.

Still, that error message is very misleading.  We should see if we can get a very direct exception message back to the consumer so they aren't scratching their heads at this one.

**Comment by benmccallum** [comment]
Weird, as you said doing `connection.Open()` works. Commenting it out fails. With the stack trace I posted. 

Is this unique to the Async variants of Dapper methods? 

We could add a check on connection.State in the `Dapper.Contexts.XyzContext::ExecuteAsync` methods. It's an enum with a bunch of options, but if it's definitely closed we could do a connection.Open(). 

It bothers me though that this is Dapper potentially handling these cases differently. What do you think?

**Comment by dougrday** [comment]
Ah.  DbConnection also has an OpenAsync() method, but the strange thing is Dapper has code to open the connection for you:

https://github.com/StackExchange/Dapper/blob/071a3fd5a0e9a3ebb9b598737b94b49c56446722/Dapper/SqlMapper.Async.cs#L388

I'm not sure why that line isn't being executed - I've seen a lot of examples where `dbConnection.OpenAsync()` is explicitly called before working with Dapper.  I think for the time being let's call it for unit tests, since it's a Dapper concern.

**Comment by benmccallum** [comment]
Hey @dougrday , looks like the issue is that for the [async versions](https://github.com/StackExchange/Dapper/blob/071a3fd5a0e9a3ebb9b598737b94b49c56446722/Dapper/SqlMapper.Async.cs#L388) of the methods Dapper try to cast the connection to a concrete DbConnection to then open it, whereas for the [standard versions](https://github.com/StackExchange/Dapper/blob/071a3fd5a0e9a3ebb9b598737b94b49c56446722/Dapper/SqlMapper.cs#L1080) they don't. It's surfacing for us because they only try open it if it's closed.

I'll download their repo tomorrow and see why they need to be casting. It could be a bug in Dapper if the cast is unnecessary or can't be made to a more generic IDbConnection.

Thanks for looking into it more. Two heads are better than one!

**Comment by benmccallum** [comment]
Yea looks like IDbConnection doesn't have an OpenAsync member...

**Comment by benmccallum** [comment]
Just found a relevant issue in Dapper here: https://github.com/StackExchange/Dapper/issues/757

**Comment by dougrday** [comment]
Looks good, thanks again :)

**Pull request merged**
